### ISSUE TITLE
Idle error in Predis when running DTC command in prod env in supervisord 

### ISSUE THREAD

**Issue by BelegUS** [mmucklo/DtcQueueBundle#106]
Setup to replicate the problem:
- `supervisord` running `dtc:queue:run --env=prod --no-debug` command in "loop" (watching for new jobs to handle)
- `redis` as a job manager in DtcQueueBundle.
- Newest version of DtcQueueBundle `master` branch

Above setup results in error being constantly written to log: `Undefined offset: 0 in {...}/vendor/mmucklo/queue-bundle/Redis/Predis.php on line 188`

Jobs are being processed without problem, so I guess those errors are thrown when there are no jobs to be handled. Still, it floods the logs so IMO could be fixed. I will try to provide such solution.

**Comment by BelegUS** [comment]
@mmucklo - any chance to get this live? Tests are passing, this is a minor (cosmetic in fact) fix, and it will save us tons of space and keep our logs sane. Now they are overran with those notices. I would prefer to stick to official version, not my fork.

**Comment by mmucklo** [comment]
@BelegUS sorry for the delay, my hands were tied up until now.

**Comment by BelegUS** [comment]
Thanks, @mmucklo! I changed the company in the meantime, but they will be happy this went live ;) Thanks for nice library!
