### ISSUE TITLE
Schedule at specific date

### ISSUE THREAD

**Issue by AngryElephant** [mmucklo/DtcQueueBundle#108]
Is it possible to schedule a job at a specific date ?

**Comment by mmucklo** [comment]
Not yet, but we could extend things as such

**Comment by mmucklo** [comment]
@AngryElephant support is available for the following job managers:

- ODM
- ORM
- Redis

Instead of using ->later(...), use the function ->at(<unix-epoch-time-in-seconds, or even microseconds in a float>)
