### ISSUE TITLE
 The "--max_count" option does not exist.

### ISSUE THREAD

**Issue by klodoma** [mmucklo/DtcQueueBundle#120]
Executing 

`bin/console dtc:queue:run --max_count 20 -v -t 3600`

you get the error 
```

/bin/console dtc:queue:run --max_count 20 -v -t 3600

In ArgvInput.php line 218:

  [Symfony\Component\Console\Exception\RuntimeException]
  The "--max_count" option does not exist.
```

![Screenshot_442](https://user-images.githubusercontent.com/944350/63763902-f077b400-c8c5-11e9-8c67-854f513f1d44.png)

**Comment by mmucklo** [comment]
Sorry, the documentation was wrong, the option should be:

```
--max-count
```

(dash instead of underscore).

I've updated the README.md to reflect that.

**Comment by klodoma** [comment]
Oh, oki doki. Thanks!
