### ISSUE TITLE
Not compatible to doctrine/mongodb-odm 2.0

### ISSUE THREAD

**Issue by thorau** [mmucklo/DtcQueueBundle#121]
The current Version 6 is not compatible to doctrine/mongodb-odm 2.0.
Are you planning to make the bundle compatible to doctrine/mongodb-odm 2.0 in the near future?

**Comment by mmucklo** [comment]
@thorau sorry for the delay, I was pretty busy the month of October - yes that's possible, but you're also welcome to submit a PR if I don't get to it soon enough for you.

**Comment by mmucklo** [comment]
@thorau - Should be fixed as of version 6.0.3
