### ISSUE TITLE
Can't seem to figure out batch mode

### ISSUE THREAD

**Issue by kevin-ian** [mmucklo/DtcQueueBundle#130]
Hi,

I searched everywhere, but couldn't find an answer. Below is the code I'm using to create batch.

```
$worker->batchLater()->createFile($file->getId());
```
I have two job with the same method name in the table `dtc_queue_job`

But when I run `php bin/console dtc:queue:run`, only one job is executed, and then it stops there. The other job is still flagged as `new` .. I have to run the command once again.

I thought batch mode would run all job having the same method name.

Am I missing something?

Futhermore, how do we know in the table that a job are batched?

Thanks in advance for the help

**Comment by kevin-ian** [comment]
Maybe it's because the two jobs doesn't have the same arguments.

**Comment by mmucklo** [comment]
That’s correct, the check for batch includes the arguments.

**Comment by kevin-ian** [comment]
Yes, thanks. I'm closing this.
