### ISSUE TITLE
Error using this bundle without GridBundle

### ISSUE THREAD

**Issue by bramalho** [mmucklo/DtcQueueBundle#132]
Due to the fact that you are using GridBundle in ODM LiveJobsGridSource.
I suggest adding this GridBundle to the composer

https://github.com/mmucklo/DtcQueueBundle/blob/2f78cf07b525e84d57f1020bfcd439881af62a44/ODM/LiveJobsGridSource.php#L6

**Comment by mmucklo** [comment]
Hi, does this come up only if you use the admin interface or elsewhere?

The admin interface does depend on GridBundle, but I had a request some time back to decouple this bundle from the GridBundle for those that don't use the Admin interface, so it's not a strict requirement.

**Comment by bramalho** [comment]
Hi,
This triggers an error when I try to use this bundle standlone.
For the time being I added the GridBundle and without registering it, that's ok because I'm using ORM, not ODM
