### ISSUE TITLE
The controller for URI "/dtc_queue/" is not callable: Class "dtc_queue.controller.queue" does not exist.

### ISSUE THREAD

**Issue by Tanariel** [mmucklo/DtcQueueBundle#136]
Hello,

I'm using Symfony 3.4 and i'm getting this error with the bundle installed as version 6.3.1 

I registered the bundles and i imported the routes but i can't figure out why this is happening.

**Comment by Tanariel** [comment]
Downgrading to version 5.1.1 is solving the problem, i guess that version 6 is not anymore compatible with SF 3.4 ? 
If this is intended, should we update the composer.json or ?

**Comment by Tanariel** [comment]
ok downgrading to version 5.1.1 gets me acces to the routes but generate a new error : 

Attempted to call an undefined method named "setAnnotationReader" of class "Dtc\QueueBundle\ORM\LiveJobsGridSource".

**Comment by Tanariel** [comment]
So if you downgrade to version 5.1.1, you have to downgrade the grid bundle too to version 5.1.1 otherwise it will install the version 7 and generate this error.

**Comment by mmucklo** [comment]
@Tanariel Sorry for the delay - I made version 5.1.2 specifically for this purpose. Making things backwards compatible with 3.4 might be challenging going forward. I need to check more if it's possible.

**Comment by Tanariel** [comment]
@mmucklo Thanks a lot!

**Comment by carlos-granados** [comment]
@mmucklo I think that to solve the `Class "dtc_queue.controller.queue" does not exist` error you just need to change
```
  defaults: { _controller: dtc_queue.controller.queue::status }
```
to
```
  defaults: { _controller: dtc_queue.controller.queue:status }
```
(notice a single `:`) as this is the syntax when you use a service name for the controller. Tested on Symfony 3.4 and working fine, haven't been able to test in later versions

**Comment by mmucklo** [comment]
@Tanariel and @carlos-granados please try version 6.4.0 with the suggested patch applied.
