### ISSUE TITLE
Trends controller complaining about missing classes which are not needed in an ODM setup

### ISSUE THREAD

**Issue by carlos-granados** [mmucklo/DtcQueueBundle#140]
The Trends controller is checking if these classes exist:
`Oro\ORM\Query\AST\Platform\Functions\Mysql\Year`
`DoctrineExtensions\Query\Mysql\Year`
However, these two classes are only needed if you are using SQL. If you are using MongoDB to save your data these classes are not needed and this check should not be performed

**Comment by mmucklo** [comment]
@carlos-granados Thanks for pointing that out. I tried to make a comprehensive fix, but I need to get a test environment setup to make sure I didn't break anything.

So far I've just left it in the trends-controller-platform-fix branch and created PR #141 for it.
