### ISSUE TITLE
The processPhpRedis function in the compiler pass is called even if Redis is not available

### ISSUE THREAD

**Issue by carlos-granados** [mmucklo/DtcQueueBundle#145]
In the Redis compiler pass we do this check:

```
        if ($container->hasParameter('dtc_queue.redis.phpredis.host')) {
            $this->processPhpRedis($container);
```

The problem is that this parameter will always be set. It will just be null if PHP Redis is not available. In this case the compiler will add a definition with a class that does not exist. This is not a problem other than having an invalid definition as long as you don't try to use it. But this breaks the `lint:container` Symfony command which actually checks the types of all arguments for services

**Comment by mmucklo** [comment]
Should be fixed in version 6.6.0.
