### ISSUE TITLE
Impossible to run command with Symfony 2 (duplicate option)

### ISSUE THREAD

**Issue by wzele** [mmucklo/DtcQueueBundle#15]
Hi, 

I get an error when I launch a command. 
Here the message : "An option with shortcut "s" already exists."
In your commands, you use the option '-s' for nano_sleep but this option is already use in  the FrameworkBundle for the shell Option. 
This option is removed in 3.0

Thank you

**Comment by mmucklo** [comment]
Okay, let me make a fix, thanks for letting me know...

**Comment by mmucklo** [comment]
I think this is fixed now for 2.2.0, please verify.
