### ISSUE TITLE
is_callable

### ISSUE THREAD

**Issue by gnorby88** [mmucklo/DtcQueueBundle#3]
In the Job Model is_callable method always return true. 
https://github.com/mmucklo/DtcQueueBundle/blob/master/Model/Job.php#L348
Use is_callable method without true (syntax only) parameter:
`if (!is_callable(array($this->worker, $method)))`

And in the documentacion have a typo:

```
<service id="fibonacci_worker" class="FibonacciWorker">
    <tag name="dat_queue.worker" />
</service>
```

It is dtc not dat:
`<tag name="dtc_queue.worker" />`

**Comment by mmucklo** [comment]
Closed in PR #7
