### ISSUE TITLE
Detached document cannot be removed

### ISSUE THREAD

**Issue by mgolshan-talentnet** [mmucklo/DtcQueueBundle#41]
Hello.
This bundle looks smart and improvable.
I tried a very basic worker based on the example you put in README and it worked well. But, when I try to run a worker which manipulates DB documents, I face to an error.
I'm getting the error `Detached document cannot be removed`.

This is the trace of error:
```
() at <my_project_root>/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/MongoDBException.php:45
 Doctrine\ODM\MongoDB\MongoDBException::detachedDocumentCannotBeRemoved() at <my_project_root>/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:1779
 Doctrine\ODM\MongoDB\UnitOfWork->doRemove() at <my_project_root>/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:1739
 Doctrine\ODM\MongoDB\UnitOfWork->remove() at <my_project_root>/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentManager.php:430
 Doctrine\ODM\MongoDB\DocumentManager->remove() at <my_project_root>/vendor/mmucklo/queue-bundle/Doctrine/BaseRunManager.php:97
 Dtc\QueueBundle\Doctrine\BaseRunManager->persistRun() at <my_project_root>/vendor/mmucklo/queue-bundle/Model/RunManager.php:124
 Dtc\QueueBundle\Model\RunManager->runStop() at <my_project_root>/vendor/mmucklo/queue-bundle/Run/Loop.php:141
 Dtc\QueueBundle\Run\Loop->runLoop() at <my_project_root>/vendor/mmucklo/queue-bundle/Command/RunCommand.php:132
 Dtc\QueueBundle\Command\RunCommand->execute() at <my_project_root>/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at <my_project_root>/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:906
 Symfony\Component\Console\Application->doRunCommand() at <my_project_root>/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:224
 Symfony\Component\Console\Application->doRun() at <my_project_root>/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:77
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at <my_project_root>/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:125
 Symfony\Component\Console\Application->run() at <my_project_root>/bin/console:28
```

Any idea?

**Comment by mmucklo** [comment]
Thanks, let me take a look...

You're manipulating objects in Mongo, correct?

**Comment by mgolshan-talentnet** [comment]
Correct.
Actually, there is a process which might manipulate or not the MongoDB documents. In general, there is a communication with MongoDB.
However, I even tried to return true without taking any action with MongoDB. I still get the same error.
The status of the `job` document is changed to `running` but, it won't be moved to `job_archive` collection

**Comment by mmucklo** [comment]
Okay, I just created a test for this and couldn't reproduce it.  Are you maybe resetting the doctrine internal cache somehow when you're doing your DB manipulations?


```php
class //....
    extends \Dtc\QueueBundle\Model\Worker
{
    // ...
    private $documentManager;
    private $entityManager;
    public function __construct(DocumentManager $documentManager, EntityManagerInterface $entityManager) {
        // ...
        $this->documentManager = $documentManager;
        $this->entityManager = $entityManager;
    }

    // ...

    public function mongotest() {
        $x = new Event();
        $x->setName('something');
        $this->documentManager->persist($x);
        $x->setTimeMs((int)(microtime(true) * 1000));
        $x->setName('somethingelse');
        $this->documentManager->persist($x);
    }
```

**Comment by mmucklo** [comment]
You wouldn't happened to be calling "clear()" on the DocumentManager would you?  That would certainly do it...

Here's a similar issue where they were doing clear() after flush()
https://github.com/theofidry/AliceDataFixtures/issues/51

**Comment by mgolshan-talentnet** [comment]
Good point.
Let me take a look.
I'll update you

**Comment by mmucklo** [comment]
@mgolshan-talentnet did the suggestion work?

**Comment by mgolshan-talentnet** [comment]
Looks like you are right.
I am trying to fix the logic.
Once I got all working, I'll let you know. I'd like to share with you if anything else comes up.

**Comment by mgolshan-talentnet** [comment]
It works now.
I had to define a separate document manager which was a bit tricky.
Also, I definitely needed to use the version 4.0 of your library.
Thanks for your great bundle and being supportive

**Comment by mrvnklm** [comment]
@mgolshan-talentnet how did you do it? do you understand why you need a second entity manager to run the tasks? facing the same issue and using two entity managers looks quite unnecessary to me.
