### ISSUE TITLE
rabbitmq example dont work... 

### ISSUE THREAD

**Issue by grekpg** [mmucklo/DtcQueueBundle#59]
i use symfony 3.4 
my config 

dtc_queue:
    manager:
        job: rabbit_mq
    rabbit_mq:
        host: rabbitmq
        port: 5672
        user: root
        password: 123
#        vhost: "/" [optional defaults to "/"]
#        ssl: [optional defaults to false - toggles to use AMQPSSLConnection]
#        options: [optional options to pass to AMQPStreamConnection or AMQPSSLConnection]
#        ssl_options: [optional extra ssl options to pass to AMQPSSLConnection]
        queue_args:
            queue: 'ppm-parse'
#            passive: [optional defaults to false]
#            durable: [optional defaults to true]
#            exlusive: [optional defaults to false]
#            auto_delete: [optional defaults to false]
#        exchange_args: [optional]
#            exchange: [optional queue name]
#            type: [optional defaults to "direct"]
#            passive: [optional defaults to false]
#            durable: [optional defaults to true]
#            auto_delete: [optional defaults to false]

```
old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'root'
            password: '123'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

            #requires php_sockets.dll
            use_socket: true # default false
        another:
            # A different (unused) connection defined by an URL. One can omit all parts,
            # except the scheme (amqp:). If both segment in the URL and a key value (see above)
            # are given the value from the URL takes precedence.
            # See https://www.rabbitmq.com/uri-spec.html on how to encode values.
            url: 'amqp://guest:password@localhost:5672/vhost?lazy=1&connection_timeout=6'
    producers:
        parse_ppmconsumer:
            connection:       default
            exchange_options: {name: 'ppm-parse', type: direct}
#            parse_ppmconsumer_service:    my_app_service # no alias by default
    consumers:
        parse_ppmconsumer:
            connection:       default
            exchange_options: {name: 'ppm-parse', type: direct}
            queue_options:    {name: 'ppm-parse'}
            callback:         app.consumer.parse_ppmconsumer
            enable_logger:    true #
```
routing : 

```
dtc_queue:
    prefix:   /admin
    resource: '@DtcQueueBundle/Resources/config/routing.yml'
dtc_grid:
    prefix:   /admin
    resource: '@DtcGridBundle/Resources/config/routing.yml'
```

in http://127.0.0.1:8000/app_dev.php/admin/dtc_queue/jobs

`Unsupported manager type: rabbit_mq`

i try run jobs manager for rabbit queue. i have worker 
this work fine: php bin/console rabbitmq:consumer  parse_ppmconsumer -m 10

when try : 

```
bin/console dtc:queue:run --id=rabbit_mq
19:01:48 ERROR     [console] Error thrown while running command "dtc:queue:run --id=rabbit_mq". Message: "stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known" ["error" => ErrorException { …},"command" => "dtc:queue:run --id=rabbit_mq","message" => "stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known"] []

                                                                                                   
  [ErrorException]                                                                                 
  stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known  
```

**Comment by mmucklo** [comment]
Hm, let me take a look.

**Comment by mmucklo** [comment]
I tried to reproduce this, but couldn't.

First you don't need --id=rabbit_mq

Here's an example

```bash
root@c47b2bb6da6a:/var/www/symfony# bin/console dtc:queue:create_job fibonacci fibonacci 10
root@c47b2bb6da6a:/var/www/symfony# bin/console dtc:queue:count
Job name   New  Running  Success  Failure  Exception  Expired  Max Retries  Max Failures  Max Exceptions
all          1      N/A      N/A      N/A        N/A      N/A          N/A           N/A             N/A
Total waiting jobs: 1
root@c47b2bb6da6a:/var/www/symfony# bin/console dtc:queue:run
root@c47b2bb6da6a:/var/www/symfony# bin/console dtc:queue:count
Job name   New  Running  Success  Failure  Exception  Expired  Max Retries  Max Failures  Max Exceptions
all          0      N/A      N/A      N/A        N/A      N/A          N/A           N/A             N/A
Total waiting jobs: 0
```

Here's my config.yml for rabbit_mq:

```yaml
dtc_queue:
    beanstalkd:
        host: beanstalkd
    manager:
        job: rabbit_mq
        run: orm
    timings:
        record: true
    redis:
        phpredis:
            host: redis
    rabbit_mq:
        host: rabbitmq
        port: 5672
        user: guest
        password: guest
        vhost: "/"
```

Could you check your configuration and let me know.

Also /dtc_queue/jobs won't work for rabbit_mq as I don't have an elegant way to iterate through all the jobs in rabbit_mq, but I'm open to suggestion...

**Comment by mmucklo** [comment]
@grekpg did you see my last comment?  Have you had a chance to review the settings?

**Comment by mmucklo** [comment]
@grekpg I'm closing this since I haven't heard anything.

**Comment by mrvnklm** [comment]
I am facing the same issue:
`dtc_queue:
    orm:
        entity_manager: dtc_queue
    manager:
        job: rabbit_mq
        run: orm
        job_timing: orm
    rabbit_mq:
        host: rabbitmq
        port: 5672
        user: guest
        password: guest
    timings:
        record: true
    priority:
        max: 255
        direction: desc
    admin:
        chartjs: 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.min.js'
`

Working if I only use "job", but if I configure like above, I get an execution time exceeded error when trying to enter the webinterface.
