### ISSUE TITLE
Possibility to save exception message rather then the whole stack

### ISSUE THREAD

**Issue by pverdu** [mmucklo/DtcQueueBundle#60]
Hi,

I was wondering if there is a possibility to save only the exception message of a job rather then the whole stack trace.
I'm trying to decorate the 'dtc_queue.manager.worker' service so i can implement my own DecoratingWorkerManager where is can se the exceptionMessage to the message only, but this isn't really working atm.

Have any ideas how i can fix this?

**Comment by pverdu** [comment]
I solved this by doing the following, but maybe there is an easier solution at hand.

`# Override default WorkerManager service to use a custom class
  dtc_queue.manager.worker:
    public: true
    class: CoreBundle\Manager\QueueWorkerManager
    arguments:
        - '@dtc_queue.manager.job'
        - '@dtc_queue.event_dispatcher'
    calls:
        - [ "setLogger", ['@?logger'] ]
    tags: [{ name: monolog.logger, channel: dtc_queue }]`

**Comment by mmucklo** [comment]
I can make it an option - maybe that would perhaps be useful to someone in the future...

**Comment by pverdu** [comment]
@mmucklo Would be really nice yeah. I fixed it now by overwriting the service and works quite nice. If you can make it an option to set 'class.worker_manager' it could help alot of people in the future.
