### ISSUE TITLE
 Notice: Undefined variable: newArchive  

### ISSUE THREAD

**Issue by andrzej-tracz** [mmucklo/DtcQueueBundle#63]
Hello,
I utilizing this bundle with Symfony 4, php7.2 on ubuntu, and ORM as queue job manager, after runing
command:
php bin/console dtc:queue:run --max-count 20 -vvv
I getting following error:

  [ErrorException]                        
  Notice: Undefined variable: newArchive  

Full stack trace:
21:04:29 DEBUG     [dtc_queue] Dtc\QueueBundle\Manager\WorkerManager::addWorker - Added worker: command_worker
[]
[]
21:04:29 INFO      [dtc_queue] Staring up a new job...
[]
[]
21:04:29 INFO      [dtc_queue] No more jobs to run (0 processed so far).
[]
[]

In DtcQueueListener.php line 85:
                                          
  [ErrorException]                        
  Notice: Undefined variable: newArchive  
                                          

Exception trace:
 Dtc\QueueBundle\Doctrine\DtcQueueListener->processRun() at /var/www/vendor/mmucklo/queue-bundle/Doctrine/DtcQueueListener.php:48
 Dtc\QueueBundle\Doctrine\DtcQueueListener->preRemove() at /var/www/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:61
 Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent() at /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Event/ListenersInvoker.php:117
 Doctrine\ORM\Event\ListenersInvoker->invoke() at /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1843
 Doctrine\ORM\UnitOfWork->doRemove() at /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1799
 Doctrine\ORM\UnitOfWork->remove() at /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:618
 Doctrine\ORM\EntityManager->remove() at /var/www/var/cache/dev/ContainerTBipJDO/EntityManager_9a5be93.php:174
 EntityManager_9a5be93->remove() at /var/www/vendor/mmucklo/queue-bundle/ORM/CommonTrait.php:124
 Dtc\QueueBundle\ORM\RunManager->persist() at /var/www/vendor/mmucklo/queue-bundle/Doctrine/DoctrineRunManager.php:101
 Dtc\QueueBundle\Doctrine\DoctrineRunManager->persistRun() at /var/www/vendor/mmucklo/queue-bundle/Manager/RunManager.php:142
 Dtc\QueueBundle\Manager\RunManager->runStop() at /var/www/vendor/mmucklo/queue-bundle/Run/Loop.php:141
 Dtc\QueueBundle\Run\Loop->runLoop() at /var/www/vendor/mmucklo/queue-bundle/Command/RunCommand.php:132
 Dtc\QueueBundle\Command\RunCommand->execute() at /var/www/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /var/www/vendor/symfony/console/Application.php:883
 Symfony\Component\Console\Application->doRunCommand() at /var/www/vendor/symfony/framework-bundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/vendor/symfony/console/Application.php:241
 Symfony\Component\Console\Application->doRun() at /var/www/vendor/symfony/framework-bundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/vendor/symfony/console/Application.php:143
 Symfony\Component\Console\Application->run() at /var/www/bin/console:39

**Comment by mmucklo** [comment]
Sorry for the delay, your fix seemed right so I merged it.
