### ISSUE TITLE
How to setup my service in this bundle ?  

### ISSUE THREAD

**Issue by Nebojsaa** [mmucklo/DtcQueueBundle#65]
I have to set up a job manager for the console command that I have created. 
The console command needs from 20 - 30 minutes to finish. 
This console command is writing into the database multiple queries and let's assume that it can't be shrink-ed to a less time. 

I have all created in Symfony2.8, but I am a really newbie using it. 
So I [enter link description here][1]

  [1]: https://github.com/mmucklo/DtcQueueBundle 

I believe now, what I need to do is to connect my console command to this. How to setup my own service inside this Queue job ?

**Comment by mmucklo** [comment]
@Nebojsaa - sorry for the delay in reply.

I'm not quite sure what you're asking.  Are you trying to get things to happen in the background recurring, or are you trying to setup a new job that you offload work on and you want to call that from within a controller or another service?

Do you have any example code for what you're trying to do?

**Comment by mmucklo** [comment]
@Nebojsaa since I haven't heard back I'm going to go ahead and close this issue.
