### ISSUE TITLE
Queued job method name as "undefined"

### ISSUE THREAD

**Issue by Siba94** [mmucklo/DtcQueueBundle#66]
Hello @mmucklo, I am getting an issue after creating queued jobs. Unable to guess what is going on. After running "dtc:queue:run" command the method name changes to "undefined"

1- Suppose I am creating a job to notify users about "X" action.
![selection_105](https://user-images.githubusercontent.com/12645991/40598462-78967f60-6265-11e8-95db-0575c0c5a331.png)
3- After running "dtc:queue:run", I am getting this
![selection_106](https://user-images.githubusercontent.com/12645991/40598911-21ca1950-6268-11e8-8f77-0133c71cfd6d.png)
Can you help me to come out of this issue?

**Comment by Siba94** [comment]
Hello @mmucklo, Its a problem around cache i.e If the cache directory didn't have the writeable permission, then this issue comes up. Closing this

**Comment by mmucklo** [comment]
@Siba94 thanks for the report - is there anything I need to do?

Is there some way this can be caught in the future (and maybe a more appropriate error message pops up?)

**Comment by Siba94** [comment]
Hello @mmucklo, For now, it's working in my case but still, If you can do something like ignoring the cache directory while running that "queue: run" command or a check for permission of cache directory because changing method name to "undefined " directly is difficult for someone to find the actual reason behind it. I think you can understand what I mean to say.
If something better is there in your mind to handle this type of situation, will be appreciated.
