### ISSUE TITLE
Suggestion: Only generate migrations if ORM is configured as queue

### ISSUE THREAD

**Issue by Lobosque** [mmucklo/DtcQueueBundle#77]
I'm new to symfony and not sure what would be the best way to handle this, but I just noticed that `make:migration` generates a few tables for the `DtcQueueBundle`. However, I believe they (or at least some of them) won't ever be used if using other transport layer than the ORM.
I wonder if it would be a good idea to somehow check the configuration to see if ORM is set before adding those tables to the migration.

**Comment by mmucklo** [comment]
That's a good point.  I don't quite know how to get Doctrine / Doctrine Migrations to exclude certain directories programmatically, but I can look into it.

**Comment by mmucklo** [comment]
Added a comment to the readme about using schema_filter in your config file.  That may be all I can reasonably do for now...
