### ISSUE TITLE
The worker is not being detected while running (ODM)

### ISSUE THREAD

**Issue by mgolshan-talentnet** [mmucklo/DtcQueueBundle#81]
Hey.
I am using Doctrine ODM.
I'm able to enqueue a job. But, when I run, I get an error due to not detecting the worker
```
0 - Call to a member function setCurrentJob() on null
#0 /var/www/app/vendor/mmucklo/queue-bundle/Manager/WorkerManager.php(103): Dtc\QueueBundle\Manager\WorkerManager->runJob(Object(Dtc\QueueBundle\Document\Job))
#1 /var/www/app/vendor/mmucklo/queue-bundle/Run/Loop.php(133): Dtc\QueueBundle\Manager\WorkerManager->run(NULL, NULL, true, '5b2d42ba64cf820...')
#2 /var/www/app/vendor/mmucklo/queue-bundle/Command/RunCommand.php(132): Dtc\QueueBundle\Run\Loop->runLoop(1529692858.4856, NULL, NULL, 1, NULL, 500000000)
#3 /var/www/app/vendor/symfony/console/Command/Command.php(251): Dtc\QueueBundle\Command\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/app/vendor/symfony/console/Application.php(904): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/app/vendor/symfony/framework-bundle/Console/Application.php(89): Symfony\Component\Console\Application->doRunCommand(Object(Dtc\QueueBundle\Command\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/app/vendor/symfony/console/Application.php(262): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Dtc\QueueBundle\Command\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/app/vendor/symfony/framework-bundle/Console/Application.php(75): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/app/vendor/symfony/console/Application.php(145): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/app/bin/console(44): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#10 {main}
```

I tried to dump the workers in the logs. But, it's an empty array.

This is what I have in my yaml services:
```
    App\Worker\MyCustomWorker:
        public: true
        tags:
            - {name: 'dtc_queue.worker'}
```
(I tried to set the `public` to `false` too. I got the same error.)

And, in my Worker Class, I have this for the name:
```
    public function getName(): string
    {
        return 'MyCustom';
    }
```

Any idea?

**Comment by mmucklo** [comment]
Hi can you look in your symfony cache directory and grep for the following:

For example:
```bash
cd var/cache/dev 
grep -r addWorker *
```

You should see something like this:

```bash
src/var/cache/ [master] grep -r addWorker *
dev/ContainerQvzreru/getDtcQueue_Manager_WorkerService.php:$instance->addWorker(${($_ = isset($this->services['app.worker.fibonacci']) ? $this->services['app.worker.fibonacci'] : $this->load(__DIR__.'/getApp_Worker_FibonacciService.php')) && false ?: '_'});
dev/appDevDebugProjectContainer.xml:      <call method="addWorker">
dev/ContainerDgapgno/getDtcQueue_Manager_WorkerService.php:$instance->addWorker(${($_ = isset($this->services['app.worker.fibonacci']) ? $this->services['app.worker.fibonacci'] : $this->load(__DIR__.'/getApp_Worker_FibonacciService.php')) && false ?: '_'});
```

Second can you show me what's being enqueued into your datastore's dtc_queue_job table/collection/etc after you enqueue a job?

E.g.

```json
> db.job.find()
{ "_id" : ObjectId("5b2e75836dd3e001aa584d63"), "worker_name" : "fibonacci", "class_name" : "AppBundle\\Worker\\FibonacciWorker", "method" : "fibonacci", "status" : "new", "args" : { "0" : "10" }, "batch" : true, "priority" : 254, "crcHash" : "0defb22ab1662f463e36e26990eb2f83e9356e909112ecd8e5dacc119d0b3fa1", "whenAt" : ISODate("2018-06-23T16:29:55.140Z"), "expiresAt" : null, "startedAt" : null, "finishedAt" : null, "elapsed" : null, "message" : null, "createdAt" : ISODate("2018-06-23T16:29:55.171Z"), "updatedAt" : ISODate("2018-06-23T16:29:55.667Z"), "maxDuration" : null, "runId" : null, "stalls" : 0, "maxStalls" : 2, "failures" : 0, "maxFailures" : 1, "exceptions" : 0, "maxExceptions" : 2, "retries" : 0, "maxRetries" : 3 }
```

**Comment by mgolshan-talentnet** [comment]
Hey @mmucklo.
Thanks for taking a look quickly.
Actually, when I run the command `grep -r addWorker *` I just get a file matched result like this: `Binary file profiler/24/df/40df24 matches`

It does not show any info in the terminal.
However, I opened the file and there is a bunch of serialized data there.
I tried to find the `addWorker` place and prettified around it and you can find it here:
```
i: 81;a: 6: {
	s: 9: "timestamp";i: 1529697671;s: 7: "message";s: 79: "Dtc\QueueBundle\Manager\WorkerManager::addWorker - Added worker: GoogleJobMatch";s: 8: "priority";i: 100;s: 12: "priorityName";s: 5: "DEBUG";s: 7: "context";a: 0: {}
	s: 7: "channel";s: 9: "dtc_queue";
}
i: 82;a: 6: {
	s: 9: "timestamp";i: 1529697673;s: 7: "message";s: 181: "MongoDB query: {"
	find ":true,"
	query ":{"
	method ":"
	reverseMatch ","
	status ":"
	new ","
	args.0 ":"
	globe_co ","
	args.1 ":"
	5 b2d285e64cf82010b2d6dd6 "},"
	fields ":[],"
	db ":"
	dtc_queue ","
	collection ":"
	job "}";s: 8: "priority";i: 100;s: 12: "priorityName";s: 5: "DEBUG";s: 7: "context";a: 0: {}
	s: 7: "channel";s: 8: "doctrine";
}
i: 83;a: 6: {
	s: 9: "timestamp";i: 1529697673;s: 7: "message";s: 820: "MongoDB query: {"
	batchInsert ":true,"
	num ":1,"
	data ":{"
	00000000106 c7a35000000001f69edad ":{"
	_id ":{"
	$id ":"
	5 b2d558964cf82001a140a6b "},"
	worker_name ":"
	GoogleJobMatch ","
	class_name ":"
	App\\ Worker\\ MyCustomWorker ","
	method ":"
	reverseMatch ","
	status ":"
	new ","
	args ":{"
	0 ":"
	globe_co ","
	1 ":"
	5 b2d285e64cf82010b2d6dd6 "},"
	batch ":false,"
	priority ":null,"
	crcHash ":"
	15 c4ca2a92cf0265cb13df206e1a40e67f73b757ca849c2f0c4a62959cc1908d ","
	whenAt ":{"
	sec ":1529697673,"
	usec ":275000},"
	expiresAt ":null,"
	startedAt ":null,"
	finishedAt ":null,"
	elapsed ":null,"
	message ":null,"
	createdAt ":{"
	sec ":1529697673,"
	usec ":278000},"
	updatedAt ":{"
	sec ":1529697673,"
	usec ":280000},"
	maxDuration ":null,"
	runId ":null,"
	stalls ":0,"
	maxStalls ":2,"
	failures ":0,"
	maxFailures ":1,"
	exceptions ":0,"
	maxExceptions ":2,"
	retries ":0,"
	maxRetries ":3}},"
	options ":[],"
	db ":"
	dtc_queue ","
	collection ":"
	job "}";s: 8: "priority";i: 100;s: 12: "priorityName";s: 5: "DEBUG";s: 7: "context";a: 0: {}
	s: 7: "channel";s: 8: "doctrine";
}
```

Also, I enqueued a job again and this is the result of query:
```
{
	"_id" : ObjectId("5b30e347c971a2000d20cb23"),
	"worker_name" : "MyCustom",
	"class_name" : "App\\Worker\\MyCustomWorker",
	"method" : "reverseMatch",
	"status" : "new",
	"args" : {
		"0" : "globe_co",
		"1" : "5b2d285e64cf82010b2d6dd6"
	},
	"batch" : false,
	"priority" : null,
	"crcHash" : "15c4ca2a92cf0265cb13df206e1a40e67f73b757ca849c2f0c4a62959cc1908d",
	"whenAt" : ISODate("2018-06-25T08:42:47.598-04:00"),
	"expiresAt" : null,
	"startedAt" : null,
	"finishedAt" : null,
	"elapsed" : null,
	"message" : null,
	"createdAt" : ISODate("2018-06-25T08:42:47.601-04:00"),
	"updatedAt" : ISODate("2018-06-25T08:42:47.604-04:00"),
	"maxDuration" : null,
	"runId" : null,
	"stalls" : 0,
	"maxStalls" : 2,
	"failures" : 0,
	"maxFailures" : 1,
	"exceptions" : 0,
	"maxExceptions" : 2,
	"retries" : 0,
	"maxRetries" : 3
}
```

**Comment by mmucklo** [comment]
Ok, @mgolshan-talentnet,

From the Mongo query it looks like the mongo query is being done on the wrong worker name (GoogleJobMatch instead of MyCustom).

What's the command line you're using to run things?

**Comment by mgolshan-talentnet** [comment]
Oh. I'm sorry for the confusion. Actually, the class name is `GoogleJobMatchWorker` and the worker name is `GoogleJobMatch`

I renamed all the names to `MyCustom` before pasting them here. I missed that one.

**Comment by mmucklo** [comment]
@mgolshan-talentnet ok.

So it looks like there's nothing in the cache directory when you did a grep - are you sure that's the right symfony cache directory for your app?

Also are you passing any WorkerName or MethodName filters during your "dtc:queue:run"

**Comment by mgolshan-talentnet** [comment]
As an update, this time, I run the command and passed the `worker-name` argument. it didn't throw the exception message in terminal. But, in DB, it stored the same exception as `message`

**Comment by mmucklo** [comment]
@mgolshan-talentnet 

So when the cache is warmed up there should be an addWorker method call added to the instantiation of the WorkerManager.

Do you have the ability to do any debugging?

I could should you some areas to trace to see what’s going on...

If you can xdebug and step through code that’s the best, if not maybe doing some var_dumps or print outs could work.

**Comment by mgolshan-talentnet** [comment]
Sure.
FYI, in `vendor/mmucklo/queue-bundle/Manager/WorkerManager.php`, inside the method `runJob`, I added this line:
`$this->log('debug', "Workers: {" . var_export($this->getWorkers(), true) . '}', [$job->getWorkerName()]);`

It always returns an empty array.

I really appreciate your help.
I'm available tomorrow to do more debugging if tell me what in where should be dumped.
Or, I can provide you team viewer connection if you prefer to do it by yourself.

At what time tomorrow, you have time to help? (please provide me the time zone too)

**Comment by mmucklo** [comment]
The code to trace is starting around line 114 in this file - 

https://github.com/mmucklo/DtcQueueBundle/blob/master/DependencyInjection/Compiler/WorkerCompilerPass.php#L114

You need to make sure the code on line 128 is called for your service.

You could try doing a cache:clear then calling dtc:queue:run with some var_dump statements around there to see if that’s the case.

If not then there could be several problems depending on what you find:

1. Service’s compiler pass is not being called on warmup (if you never reach line 114 even that would be he likely issue)
2. The tag is wrong or not detected by symfony for some reason (if you reach 114 but not 128)
3. The service added is not being recorded in the cache for some reason

**Comment by mmucklo** [comment]
@mgolshan-talentnet 

I could do a remote debug tomorrow if still needed at 7a PST, but would need to know tonight.

If there’s a way to PM me on github please do so with further details on how to reach you.

**Comment by mgolshan-talentnet** [comment]
7am PST sounds great.
Looks like `setupTaggedServices` is not being called.
I don't think I can send you any private message.
Please send me an email to mgolshan-at-talentnet.com (replace `-at-` with `@`)

Tomorrow morning, I send you team viewer connection details. (btw, I'll remove my email address from this comment after your confirmation 😉 )

**Comment by mmucklo** [comment]
Sent instructions to reach me.

**Comment by mmucklo** [comment]
Okay to close the loop on this, the issue was in symfony 4 - adding a worker service to the dtc_queue.yaml file directly doesn't seem to work, in that symfony doesn't seem to pick it up as it isn't registered as a tagged services.

If you add it to services.yaml instead, it seems to be fine.

**Comment by mgolshan-talentnet** [comment]
Yes.
And, thanks for helping on that and saved my life 😉
