### ISSUE TITLE
Admin pages broken UI

### ISSUE THREAD

**Issue by gszabo** [mmucklo/DtcQueueBundle#89]
Hello!

After following the installation instructions, the admin pages look like this:

![image](https://user-images.githubusercontent.com/5555420/42574052-00b96242-851e-11e8-885c-2ba2a311fd42.png)

Navigation header is not styled at all, search box overlaps with table, etc. It seems like some style is missing, but it does not look like the screenshot in the readme.

What could we possibly be missing?

**Comment by mmucklo** [comment]
@gszabo I think it's an issue with bootstrap4.  I'll try to get to it within the next day or so.

**Comment by mmucklo** [comment]
@gszabo - I had an error in the dtc_grid.yaml recipe.  I've opened a PR aga

Please try this config for dtc_grid.yaml (config/packages/dtc_grid.yaml):

https://github.com/mmucklo/recipes-contrib/blob/mmucklo/grid-bundle/mmucklo/grid-bundle/4.0/config/packages/dtc_grid.yaml

There's probably some additional nav styling that will have to be fixed afterwards, however.

**Comment by gszabo** [comment]
Thank you @mmucklo, bumping those bootstrap versions fixed the overlapping issues. As you predicted, the navbar is still unstyled.

**Comment by gszabo** [comment]
@mmucklo - I played with the `nav.html.twig` file to make it look like the latest bootstrap navigation markup. 

This is the result, in case it might be useful. The color and background-color might need to be different to fit into the theme. 

```html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">DtcQueue</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {%  if app.request.get('_route') == 'dtc_queue_jobs' %}active{% endif %}"><a class="nav-link" href="{{ path('dtc_queue_jobs') }}">Waiting Jobs{% if app.request.get('_route') == 'dtc_queue_jobs' %} <span class="sr-only">(current)</span>{% endif %}</a></li>
            <li class="nav-item {%  if app.request.get('_route') == 'dtc_queue_jobs_running' %}active{% endif %}"><a class="nav-link" href="{{ path('dtc_queue_jobs_running') }}">Running Jobs{% if app.request.get('_route') == 'dtc_queue_jobs_running' %} <span class="sr-only">(current)</span>{% endif %}</a></li>
            <li class="nav-item {%  if app.request.get('_route') == 'dtc_queue_jobs_all' %}active{% endif %}"><a class="nav-link" href="{{ path('dtc_queue_jobs_all') }}">All Jobs{% if app.request.get('_route') == 'dtc_queue_jobs_all' %} <span class="sr-only">(current)</span>{% endif %}</a></li>
            <li class="nav-item {%  if app.request.get('_route') == 'dtc_queue_runs' %}active{% endif %}"><a class="nav-link" href="{{ path('dtc_queue_runs') }}">Runs{% if app.request.get('_route') == 'dtc_queue_runs' %} <span class="sr-only">(current)</span>{% endif %}</a></li>
            <li class="nav-item {%  if app.request.get('_route') == 'dtc_queue_status' %}active{% endif %}"><a class="nav-link" href="{{ path('dtc_queue_queue_status') }}">Status{% if app.request.get('_route') == 'dtc_queue_status' %} <span class="sr-only">(current)</span>{% endif %}</a></li>
            <li class="nav-item {%  if app.request.get('_route') == 'dtc_queue_workers' %}active{% endif %}"><a class="nav-link" href="{{ path('dtc_queue_workers') }}">Workers{% if app.request.get('_route') == 'dtc_queue_workers' %} <span class="sr-only">(current)</span>{% endif %}</a></li>
            <li class="nav-item {%  if app.request.get('_route') == 'dtc_queue_trends' %}active{% endif %}"><a class="nav-link" href="{{ path('dtc_queue_trends') }}">Trends{% if app.request.get('_route') == 'dtc_queue_trends' %} <span class="sr-only">(current)</span>{% endif %}</a></li>
        </ul>
    </div>
</nav>

```

**Comment by mmucklo** [comment]
@gszabo Thanks, I'll try to get to it later today if not tomorrow.

**Comment by mmucklo** [comment]
@gszabo - Thanks for your patience.  I have a fix in the master branch.  I need to create a 5.0 tag, but I'm waiting for https://github.com/symfony/recipes-contrib/pull/420 to be merged first.

**Comment by knifeofdreams** [comment]
@mmucklo Thank you so much for being so quick with this fix. We are looking forward to the merge with @gszabo 😊 Have a great week!

**Comment by maikelreyes** [comment]
This issue is already committed?

**Comment by mmucklo** [comment]
This should be fixed by now. Please reopen or create a new issue if not.
