### ISSUE TITLE
Links to assets do not work

### ISSUE THREAD

**Issue by metalmini** [mmucklo/DtcQueueBundle#94]
We have a Symfony 3.4 app with Encore and i can't seem to find how i can get the assets in de admin interface to work.

Is there a copy or publish command, or should there be one? These hard coded links to assets or not really necessary, i would think? Or are there CDN urls for the js files?
 
In jobs_running.html.twig
`<script src="/bundles/dtcqueue/js/jobs.js?v=4"></script>`

**Comment by mmucklo** [comment]
@metalmini I think someone fixed this? in PR #93 maybe?

If you're still using the bundle could you verify (sorry I was not able to respond when you wrote in about this).
